# Generated by Django 2.2.3 on 2020-02-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_time',
            new_name='create_time',
        ),
    ]
